baseurl = "http://blog.syundo.org"
languageCode = "ja"
title = "ROBO LOG"
disqusShortname = "robolog"
pygmentscodefences = true
pygmentsstyle = "paraiso-light"

[Params]
subtitle = "つくりたいものをつくる"
twitter = "https://twitter.com/ksyundo"
github = "https://github.com/syundo0730"
profile = "/images/profile.jpeg"
copyright = "Written by Shundo Kishi"
analytics = "UA-21014159-4"
